configure nix and update github workflows
Effect-TS/match pull request #188
Opened 2023-10-01 09:23 UTC by fubhy

2023-10-01 20:11 UTC, tim-smart requested changes

2023-10-01 20:11 UTC, tim-smart commented on package.json
> +    "effect": "^2.0.0-next.39"
We will need to not use caret versions here, as we no longer have a way to signal breaking changes in the `effect` package. We will have to assume every new alpha version contains breaking changes.

2023-10-02 00:17 UTC, fubhy commented on package.json
> +    "effect": "^2.0.0-next.39"
Hmmm. That means loads of peer dep warnings and potentially other issues unless we always bump all ecosystem packages together.

2023-10-02 01:47 UTC, fubhy commented on package.json
> +    "effect": "^2.0.0-next.39"
As a user of a prerelease software I think i would be much more open to breaking api changes of said software than opaque double dependency or other similar issues caused by inconsistent dependency versions. Double package hazard is not the only issue here ... Happy.to elaborate in discord in the morning ... I think this (carret semver range) is the lesser evil at this stage of development.

2023-10-31 17:27 UTC, closed without merging