add missing examples
Effect-TS/match pull request #19
Opened 2023-02-08 19:54 UTC by datner

and fix the broken link for Option

2023-02-08 22:03 UTC, tim-smart requested changes

2023-02-08 22:03 UTC, tim-smart commented on README.md
> +A Matcher that marks the end of the matcher and allows to provide a fallback value if a no matchers hit. Returns the match.
`provide a fallback value if a no patterns match`

Also same as above regarding `Returns the match`

2023-02-08 22:03 UTC, tim-smart commented on README.md
> +A Matcher that _might_ match a value. Returns an [Either](https://github.com/fp-ts/core/blob/main/guides/Either.md) in the shape of `Either<OriginalInput, MatchResult>`.
`Either<NoMatchResult, MatchResult>`

The input type will be narrowed as much as possible.

2023-02-12 23:25 UTC, datner commented on README.md
> +A Matcher that marks the end of the matcher and allows to provide a fallback value if a no matchers hit. Returns the match.
I was having a stroke while writing this apparently

2023-02-12 23:38 UTC, tim-smart approved these changes

2023-02-12 23:39 UTC, tim-smart commented
Thanks!

2023-02-12 23:39 UTC, merged